### ISSUE TITLE
GIoU value 

### ISSUE THREAD

**Issue by burui11087** [generalized-iou/g-tensorflow-models#4]
Hi, I have a question about GIoU value. The Fig. 3 in your paper shows that GIoU will be from 0 to 0.2 when IoU is 0.2, but I find it's not exact, GIoU will smaller than 0 sometimes.

Do I misunderstand Fig. 3? 

Thanks in advanced.

**Comment by shrezatofighi** [comment]
Yes, you are right. Fig. 3 is plotted when both bounding box sizes are fixed and the centers are variable only. We clarified this in the updated manuscript. When both size and centers are variables, the plot for GIoU vs IoU would be very similar, except it appears to be a ticker region .
